apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  completions: 1
  template:
    metadata:
      labels:
        app: run
    spec:
      restartPolicy: OnFailure
      containers:
        - image: hero2510/migrate-app
          name: migrate
          command:
            - "/app/run"
            - migrate 
          env:
            - name: POSTGRES_DNS
              value: postgres://crawler:200lab@postgres-0.postgres:5432/crawler?sslmode=disable
